[palgen]
output = "build"

[palgen.extensions]
folders = ["tools"]
inline = false

[project]
name = "librepr"
version = "0.1"
sources = ["include", "benchmark"]

[amalgamate]
root = "repr"
filename = "amalgamated.h"

[benchmark]
output = "build/benchmark"
repeat_each = 5

[graphs]
input = "build/benchmark"
output = "build/docs/html/benchmark"
summary_url = "https://github.com/Tsche/repr.wiki.git"

[docs]
style_output = "build/docs/style"
style_url = "https://github.com/jothepro/doxygen-awesome-css.git"
style_tag = "v2.3.1"

extensions_output = "build/docs/extensions"
extensions_url = "https://github.com/Tsche/doxygen-utils.git"
extensions_tag = "master"